### ISSUE TITLE
Unable to download pre-trained model

### ISSUE THREAD

**Issue by Shivvrat** [hwang1996/SGN#2]
I tried downloading the pre-trained model but it gave me this error. 

User account '' from identity provider '' does not exist in tenant 'Nanyang Technological University' and cannot access the application '08e18876-6177-487e-b8b5-cf950c1e598c'.

Can you please let me know if I can get the pre-trained model from somewhere else?

**Comment by hwang1996** [comment]
Please try this [link](https://drive.google.com/file/d/1oT1dKCTznZ2xW_ZgVbCAxd5EEwtacxuF/view?usp=share_link), thanks.
